version: 1
formatters:
  custom_formatter:
    (): krakmeopen.formatter.CustomFormatter
    fmt: "%(asctime)s : %(name)s : %(levelname)-10s %(msg)s"  # default fmt
    info_format: '%(asctime)s : %(levelname)-10s %(msg)s'     # INFO specific format
    datefmt: "%Y-%m-%d [%H:%M:%S]"                            # datefmt for all levels
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: custom_formatter
loggers:
  krakmeopen:
    level: INFO
    handlers: [console]
    propagate: no
  metrics:
    level: INFO
    handlers: [console]
    propagate: no
  kmers:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
